### ISSUE TITLE
App Crash when the back button is tapped

### ISSUE THREAD

**Issue by hosaysg** [kmcgill88/admob_flutter#118]
This plugin is causing the following crash issues whenever the back button is tapped on a view with the banner view loaded. Is there a way to correctly dispose the banner?

Fatal Exception: java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
       at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:227)
       at io.flutter.embedding.engine.FlutterJNI.markTextureFrameAvailable(FlutterJNI.java:554)
       at io.flutter.embedding.engine.renderer.FlutterRenderer.markTextureFrameAvailable(FlutterRenderer.java:274)
       at io.flutter.embedding.engine.renderer.FlutterRenderer.access$300(FlutterRenderer.java:38)
       at io.flutter.embedding.engine.renderer.FlutterRenderer$SurfaceTextureRegistryEntry$1.onFrameAvailable(FlutterRenderer.java:145)
       at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:206)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by heshaShawky** [comment]
This happening to me too with the same error too, the problem comes when putting a banner ad on the home screen and closing the app by the back native button!

**Comment by hosaysg** [comment]
> This happening to me too with the same error too, the problem comes when putting a banner ad on the home screen and closing the app by the back native button!

Yes, exactly. Otherwise, this plugin is working flawlessly.  Please fix this issue soon.  Thanks.

**Comment by EliasDeuss** [comment]
@hosaysg @heshaShawky Are you disposing the ads in ```dispose()``` ?

**Comment by hosaysg** [comment]
> @hosaysg @heshaShawky Are you disposing the ads in `dispose()` ?
> 
> Also could be flutter: [flutter/flutter#28651](https://github.com/flutter/flutter/issues/28651)

There doesn’t seem to be a way to dispose the ads so I did not do it in the dispose() function.

**Comment by heshaShawky** [comment]
> @hosaysg @heshaShawky Are you disposing the ads in `dispose()` ?
> 
> Also could be flutter: [flutter/flutter#28651](https://github.com/flutter/flutter/issues/28651)

there's no way to dispose of the Banner ads on the documentation provided [here](https://github.com/kmcgill88/admob_flutter/wiki/Banner-Ads) 

Also, No,  it's not related to that issue as once I remove the bannerAd widget from the home screen no issues happening ( crashing ) to my app. 

I'm using now the interstitial add instead until this issue gets solved.

**Comment by heshaShawky** [comment]
Why no updates in this? 
please, I have multiple apps waiting to publish based on that issue. 

Thanks.

**Comment by oberon168** [comment]
Any dispose function that can be used to clean up before exit?

**Comment by tonypottera24** [comment]
Same issue

**Comment by hobiyazilim** [comment]
> This plugin is causing the following crash issues whenever the back button is tapped on a view with the banner view loaded. Is there a way to correctly dispose the banner?
> 
> ```
> Fatal Exception: java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
>        at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:227)
>        at io.flutter.embedding.engine.FlutterJNI.markTextureFrameAvailable(FlutterJNI.java:554)
>        at io.flutter.embedding.engine.renderer.FlutterRenderer.markTextureFrameAvailable(FlutterRenderer.java:274)
>        at io.flutter.embedding.engine.renderer.FlutterRenderer.access$300(FlutterRenderer.java:38)
>        at io.flutter.embedding.engine.renderer.FlutterRenderer$SurfaceTextureRegistryEntry$1.onFrameAvailable(FlutterRenderer.java:145)
>        at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:206)
>        at android.os.Handler.dispatchMessage(Handler.java:106)
>        at android.os.Looper.loop(Looper.java:164)
>        at android.app.ActivityThread.main(ActivityThread.java:6494)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
> ```

**Comment by hobiyazilim** [comment]
plugins I tried to add and try. I encountered the same problem in all of them. There is no problem when there is no internet connection.
admob_flutter: "^0.3.4"
native_flutter_admob

**Comment by heshaShawky** [comment]
Any updates with this guys?

**Comment by hobiyazilim** [comment]
import 'package:admob_flutter/admob_flutter.dart';
import 'package:flutter/material.dart';
import 'AcApp.dart';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
     appBar:AppBar(title: Text("flutter admob remover"),),
      body:Center(child:WsAd( ),),),
    );
  }
}



class WsAd extends StatefulWidget {
  const WsAd( {Key key }) : super(key: key);


  @override
  _MyAppState createState() => _MyAppState();

}

class _MyAppState extends State<WsAd> with WidgetsBindingObserver {

  bool show = true;
  @override
  void initState() {
    super.initState();
    show = true;
    print('************************ initState ************************');
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void deactivate() {
    super.deactivate();
    //this method not called when user press android back button or quit
    print('************************ deactivate ************************');
  }

  @override
  void dispose() {
    super.dispose();

    WidgetsBinding.instance.removeObserver(this);


    //this method not called when user press android back button or quit
    print('************************ dispose ************************');
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    //print inactive and paused when quit

    print(" ************************ ");
    print(state);
    if (state == AppLifecycleState.inactive) {
      setState(() {
        show = false;
        print("setstate  : show = "+  show.toString());
      });
    }
    print(" ************************ ");
//      maestro.gSm.gsmAds.controller.dispose();
//      Clinvoke.disposeAdmob_flutter();

//      exit(0);

  }


  @override
  Widget build(BuildContext context) {
    return show ? Container(height: 60,width: 350,child: AdmobBanner(
        adUnitId: AcApp.testBanner, adSize: AdmobBannerSize.BANNER) ) : Container(height: 0,width: 0,);
  }

}



it works

**Comment by hobiyazilim** [comment]
``import 'package:admob_flutter/admob_flutter.dart';
import 'package:flutter/material.dart';
import 'AcApp.dart';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
// This widget is the root of your application.
@override
Widget build(BuildContext context) {
return MaterialApp(
title: 'Flutter Demo',
home: Scaffold(
appBar:AppBar(title: Text("flutter admob remover"),),
body:Center(child:WsAd( ),),),
);
}
}

class WsAd extends StatefulWidget {
const WsAd( {Key key }) : super(key: key);

@override
_MyAppState createState() => _MyAppState();

}

class _MyAppState extends State with WidgetsBindingObserver {

bool show = true;
@override
void initState() {
super.initState();
show = true;
print('************************ initState ************************');
WidgetsBinding.instance.addObserver(this);
}

@override
void deactivate() {
super.deactivate();
//this method not called when user press android back button or quit
print('************************ deactivate ************************');
}

@override
void dispose() {
super.dispose();

WidgetsBinding.instance.removeObserver(this);


//this method not called when user press android back button or quit
print('************************ dispose ************************');
}

@override
void didChangeAppLifecycleState(AppLifecycleState state) {
//print inactive and paused when quit

print(" ************************ ");
print(state);
if (state == AppLifecycleState.inactive) {
  setState(() {
    show = false;
    print("setstate  : show = "+  show.toString());
  });
}
print(" ************************ ");
// maestro.gSm.gsmAds.controller.dispose();
// Clinvoke.disposeAdmob_flutter();

// exit(0);

}

@override
Widget build(BuildContext context) {
return show ? Container(height: 60,width: 350,child: AdmobBanner(
adUnitId: AcApp.testBanner, adSize: AdmobBannerSize.BANNER) ) : Container(height: 0,width: 0,);
}

}

**Comment by rubenaalders** [comment]
Hiding the banner before closing the app does indeed seem as a workaround as mentioned by @hobiyazilim.

**Comment by pamir72** [comment]
Not just banner. I hide google map before exit app with @hobiyazilim workaround and it works. But would like to see the flutter team solve the problem.

**Comment by mathias22osterhagen22** [comment]
Same issue here, still not fixed.

Works when the banner Widget is not displayed.

**Comment by mathias22osterhagen22** [comment]
@hob
```dart
import 'package:admob_flutter/admob_flutter.dart';
import 'package:flutter/material.dart';
import 'AcApp.dart';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
    // This widget is the root of your application.
    @override
    Widget build(BuildContext context) {
        return MaterialApp(
            title: 'Flutter Demo',
            home: Scaffold(
                appBar: AppBar(title: Text("flutter admob remover"), ),
                body: Center(child: WsAd(), ), ),
        );
    }
}

class WsAd extends StatefulWidget {
    const WsAd({
        Key key
    }): super(key: key);

    @override
    _MyAppState createState() => _MyAppState();

}

class _MyAppState extends State with WidgetsBindingObserver {

    bool show = true;
    @override
    void initState() {
        super.initState();
        show = true;
        print('************************ initState ************************');
        WidgetsBinding.instance.addObserver(this);
    }

    @override
    void deactivate() {
        super.deactivate();
        //this method not called when user press android back button or quit
        print('************************ deactivate ************************');
    }

    @override
    void dispose() {
        super.dispose();

        WidgetsBinding.instance.removeObserver(this);

        //this method not called when user press android back button or quit
        print('************************ dispose ************************');
    }

    @override
    void didChangeAppLifecycleState(AppLifecycleState state) {
        //print inactive and paused when quit

        print(" ************************ ");
        print(state);
        if (state == AppLifecycleState.inactive) {
            setState(() {
                show = false;
                print("setstate : show = " + show.toString());
            });
        }
        print(" ************************ ");
        // maestro.gSm.gsmAds.controller.dispose();
        // Clinvoke.disposeAdmob_flutter();

        // exit(0);

    }

    @override
    Widget build(BuildContext context) {
        return show ? Container(height: 60, width: 350, child: AdmobBanner(
            adUnitId: AcApp.testBanner, adSize: AdmobBannerSize.BANNER)) : Container(height: 0, width: 0, );
    }

}
```
Same code above but readable

**Comment by thiagovargas** [comment]
Same problem here, but, i try to implement the solution from @hobiyazilim and the Google was blocked my ads.
So, can we solve this issue, please?

**Comment by henry2man** [comment]
> Same problem here, but, i try to implement the solution from @hobiyazilim and the Google was blocked my ads.
> So, can we solve this issue, please?

I agree, showing & hidding ads is strictly prohibited by Google Admob policies because this behaviour may cause unwanted clicks on the ads. 

Is there any other alternative? I'm experiencing this issue all the time.

**Comment by kmcgill88** [comment]
I don't believe this is an admob_flutter specific issue.

See: 
https://github.com/flutter/flutter/issues/33511#issuecomment-665095165

Hopefully the fix landed in 1.20.0 release.
