### ISSUE TITLE
UiKitView throw exception NoSuchMethodError in iOS

### ISSUE THREAD

**Issue by myriky** [kmcgill88/admob_flutter#191]
I'm using 4 stateful screens in TabBarView.
some problem occur when touch somewhere in not included AdmobBanner screen after AdmobBanner rendered.

I think there is a problem with UIKitView.

admob_banner.dart
``` 
UiKitView(
    key: _key,
    viewType: 'admob_flutter/banner',
    creationParams: <String, dynamic>{
        'adUnitId': widget.adUnitId,
        'adSize': widget.adSize.toMap,
    },
    creationParamsCodec: const StandardMessageCodec(),
    onPlatformViewCreated: _onPlatformViewCreated,
)
```

```
[+12203 ms] [DEVICE LOG] 2020-07-09 16:29:09.652891+0900  localhost Runner[22832]: (Flutter) flutter: ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞════════════════════════
[        ] [DEVICE LOG] The following NoSuchMethodError was thrown while routing a
[        ] [DEVICE LOG] pointer event:
[        ] [DEVICE LOG] The method '-' was called on null.
[        ] [DEVICE LOG] Receiver: null
[        ] [DEVICE LOG] Tried calling: -(1242.0)
[        ] [DEVICE LOG]
[        ] [DEVICE LOG] When the exception was thrown, this was the stack:
[        ] [DEVICE LOG] #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
[        ] [DEVICE LOG] #1      RenderSliverMultiBoxAdaptor.childMainAxisPosition (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:573:37)
[        ] [DEVICE LOG] #2      RenderSliverHelpers.applyPaintTransformForBoxChild (package:flutter/src/rendering/sliver.dart:1695:20)
[        ] [DEVICE LOG] #3      RenderSliverMultiBoxAdaptor.applyPaintTransform (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:586:5)
[   +1 ms] [DEVICE LOG] #4      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2345:24)
[        ] [DEVICE LOG] #5      RenderBox.globalToLocal (package:flutter/src/rendering/box.dart:2250:31)
[        ] [DEVICE LOG] #6      RenderUiKitView._handleGlobalPointerEvent (package:flutter/src/render<…>
[        ] flutter: ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞════════════════════════
[        ] The following NoSuchMethodError was thrown while routing a
[        ] pointer event:
[        ] The method '-' was called on null.
[        ] Receiver: null
[        ] Tried calling: -(1242.0)
[        ] When the exception was thrown, this was the stack:
[        ] #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
[        ] #1      RenderSliverMultiBoxAdaptor.childMainAxisPosition (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:573:37)
[        ] #2      RenderSliverHelpers.applyPaintTransformForBoxChild (package:flutter/src/rendering/sliver.dart:1695:20)
[        ] #3      RenderSliverMultiBoxAdaptor.applyPaintTransform (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:586:5)
[        ] #4      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2345:24)
[        ] #5      RenderBox.globalToLocal (package:flutter/src/rendering/box.dart:2250:31)
[        ] #6      RenderUiKitView._handleGlobalPointerEvent (package:flutter/src/render<…>
[        ] [DEVICE LOG] 2020-07-09 16:29:09.653157+0900  localhost Runner[22832]: (Flutter) flutter: Flutter error caught by Crashlytics plugin:
[        ] [DEVICE LOG] 2020-07-09 16:29:09.660925+0900  localhost Runner[22832]: (Flutter) flutter: ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY
╞═══════════════════════════════════════════════════════════
[        ] [DEVICE LOG] 2020-07-09 16:29:09.661202+0900  localhost Runner[22832]: (Flutter) flutter: The following NoSuchMethodError was thrown while routing a pointer
event:
[        ] [DEVICE LOG] 2020-07-09 16:29:09.661494+0900  localhost Runner[22832]: (Flutter) flutter: The method '-' was called on null.
[        ] [DEVICE LOG] 2020-07-09 16:29:09.661647+0900  localhost Runner[22832]: (Flutter) flutter: Receiver: null
[        ] [DEVICE LOG] 2020-07-09 16:29:09.661918+0900  localhost Runner[22832]: (Flutter) flutter: Tried calling: -(1242.0)
[        ] [DEVICE LOG] 2020-07-09 16:29:09.662607+0900  localhost Runner[22832]: (Flutter) flutter:
[        ] flutter: Flutter error caught by Crashlytics plugin:
[        ] flutter: ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
[        ] flutter: The following NoSuchMethodError was thrown while routing a pointer event:
[        ] flutter: The method '-' was called on null.
[        ] flutter: Receiver: null
[        ] flutter: Tried calling: -(1242.0)
[        ] flutter:
[        ] [DEVICE LOG] 2020-07-09 16:29:09.662867+0900  localhost Runner[22832]: (Flutter) flutter: When the exception was thrown, this was the stack:
[        ] [DEVICE LOG] 2020-07-09 16:29:09.663082+0900  localhost Runner[22832]: (Flutter) flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
[        ] [DEVICE LOG] 2020-07-09 16:29:09.663811+0900  localhost Runner[22832]: (Flutter) flutter: #1      RenderSliverMultiBoxAdaptor.childMainAxisPosition
(package:flutter/src/rendering/sliver_multi_box_adaptor.dart:573:37)
[        ] [DEVICE LOG] 2020-07-09 16:29:09.664912+0900  localhost Runner[22832]: (Flutter) flutter: #2      RenderSliverHelpers.applyPaintTransformForBoxChild
(package:flutter/src/rendering/sliver.dart:1695:20)
[        ] [DEVICE LOG] 2020-07-09 16:29:09.666434+0900  localhost Runner[22832]: (Flutter) flutter: #3      RenderSliverMultiBoxAdaptor.applyPaintTransform
(package:flutter/src/rendering/sliver_multi_box_adaptor.dart:586:5)
[        ] [DEVICE LOG] 2020-07-09 16:29:09.667180+0900  localhost Runner[22832]: (Flutter) flutter: #4      RenderObject.getTransformTo
(package:flutter/src/rendering/object.dart:2345:24)
[        ] flutter: When the exception was thrown, this was the stack:
[        ] flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
[        ] flutter: #1      RenderSliverMultiBoxAdaptor.childMainAxisPosition (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:573:37)
[        ] flutter: #2      RenderSliverHelpers.applyPaintTransformForBoxChild (package:flutter/src/rendering/sliver.dart:1695:20)
[        ] flutter: #3      RenderSliverMultiBoxAdaptor.applyPaintTransform (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:586:5)
[        ] flutter: #4      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2345:24)
[        ] [DEVICE LOG] 2020-07-09 16:29:09.667929+0900  localhost Runner[22832]: (Flutter) flutter: #5      RenderBox.globalToLocal
(package:flutter/src/rendering/box.dart:2250:31)
[        ] [DEVICE LOG] 2020-07-09 16:29:09.668148+0900  localhost Runner[22832]: (Flutter) flutter: #6      RenderUiKitView._handleGlobalPointerEvent
(package:flutter/src/rendering/platform_view.dart:354:40)
[        ] [DEVICE LOG] 2020-07-09 16:29:09.668614+0900  localhost Runner[22832]: (Flutter) flutter: #7      PointerRouter._dispatch
(package:flutter/src/gestures/pointer_router.dart:76:12)
[        ] [DEVICE LOG] 2020-07-09 16:29:09.669533+0900  localhost Runner[22832]: (Flutter) flutter: #8      PointerRouter._dispatchEventToRoutes.<anonymous closure>
(package:flutter/src/gestures/pointer_router.dart:122:9)
[        ] [DEVICE LOG] 2020-07-09 16:29:09.670383+0900  localhost Runner[22832]: (Flutter) flutter: #9      _LinkedHashMapMixin.forEach
(dart:collection-patch/compact_hash.dart:379:8)
[   +1 ms] [DEVICE LOG] 2020-07-09 16:29:09.670874+0900  localhost Runner[22832]: (Flutter) flutter: #10     PointerRouter._dispatchEventToRoutes
(package:flutter/src/gestures/pointer_router.dart:120:18)
[        ] [DEVICE LOG] 2020-07-09 16:29:09.671571+0900  localhost Runner[22832]: (Flutter) flutter: #11     PointerRouter.route
(package:flutter/src/gestures/pointer_router.dart:112:5)
[        ] [DEVICE LOG] 2020-07-09 16:29:09.672000+0900  localhost Runner[22832]: (Flutter) flutter: #12     GestureBinding.handleEvent
(package:flutter/src/gestures/binding.dart:218:19)
[        ] [DEVICE LOG] 2020-07-09 16:29:09.672924+0900  localhost Runner[22832]: (Flutter) flutter: #13     GestureBinding.dispatchEvent
(package:flutter/src/gestures/binding.dart:198:22)
[        ] [DEVICE LOG] 2020-07-09 16:29:09.673408+0900  localhost Runner[22832]: (Flutter) flutter: #14     GestureBinding._handlePointerEvent
(package:flutter/src/gestures/binding.dart:156:7)
[        ] flutter: #5      RenderBox.globalToLocal (package:flutter/src/rendering/box.dart:2250:31)
[        ] flutter: #6      RenderUiKitView._handleGlobalPointerEvent (package:flutter/src/rendering/platform_view.dart:354:40)
[        ] flutter: #7      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
[        ] flutter: #8      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
[        ] flutter: #9      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
[        ] flutter: #10     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
[        ] flutter: #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:112:5)
[        ] flutter: #12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
[        ] flutter: #13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
[        ] flutter: #14     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
[        ] [DEVICE LOG] 2020-07-09 16:29:09.674713+0900  localhost Runner[22832]: (Flutter) flutter: #15     GestureBinding._flushPointerEventQueue
(package:flutter/src/gestures/binding.dart:102:7)
[        ] [DEVICE LOG] 2020-07-09 16:29:09.674956+0900  localhost Runner[22832]: (Flutter) flutter: #16     GestureBinding._handlePointerDataPacket
(package:flutter/src/gestures/binding.dart:86:7)
[        ] [DEVICE LOG] 2020-07-09 16:29:09.675109+0900  localhost Runner[22832]: (Flutter) flutter: #20     _invoke1 (dart:ui/hooks.dart:275:10)
[        ] [DEVICE LOG] 2020-07-09 16:29:09.675413+0900  localhost Runner[22832]: (Flutter) flutter: #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
[        ] [DEVICE LOG] 2020-07-09 16:29:09.675978+0900  localhost Runner[22832]: (Flutter) flutter: (elided 3 frames from dart:async)
[        ] [DEVICE LOG] 2020-07-09 16:29:09.676849+0900  localhost Runner[22832]: (Flutter) flutter:
[        ] [DEVICE LOG] 2020-07-09 16:29:09.677257+0900  localhost Runner[22832]: (Flutter) flutter: Event:
[        ] [DEVICE LOG] 2020-07-09 16:29:09.677785+0900  localhost Runner[22832]: (Flutter) flutter:   PointerDownEvent#e8f01(position: Offset(283.0, 393.0))
[        ] [DEVICE LOG] 2020-07-09 16:29:09.678753+0900  localhost Runner[22832]: (Flutter) flutter:
════════════════════════════════════════════════════════════════════════════════════════════════════
[        ] flutter: #15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
[        ] flutter: #16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
[        ] flutter: #20     _invoke1 (dart:ui/hooks.dart:275:10)
[        ] flutter: #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
[        ] flutter: (elided 3 frames from dart:async)
[        ] flutter:
[        ] flutter: Event:
[        ] flutter:   PointerDownEvent#e8f01(position: Offset(283.0, 393.0))
[        ] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[        ] [DEVICE LOG] 2020-07-09 16:29:09.687612+0900  localhost Runner[22832]: (Flutter) flutter: firebase_crashlytics: Error reported to Crashlytics.
[        ] flutter: firebase_crashlytics: Error reported to Crashlytics.
```

```

```
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/Riky/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/Riky/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 31.3.2
    • Dart plugin version 182.3569.4

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (2 available)
    • iPhone    • a0c20bde5b5b9cc440300c6d3c9679dc61e5b269 • ios • iOS 12.4.5
    • iPhone 11 • 3FE70D39-5B47-477A-814A-98DBE6FB9E6F     • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5
      (simulator)

! Doctor found issues in 1 category.
```
```
any ideas?

**Comment by kmcgill88** [comment]
`The method '-' was called on null.` looks strange. I'm not sure what would cause this. Have you made any progress on it?
