### ISSUE TITLE
env: sh\r: No such file or directory

### ISSUE THREAD

**Issue by willladislaw** [kmcgill88/admob_flutter#251]
```
[+34039 ms] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':app:processDebugResources'.
[        ] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[        ]    > Android resource linking failed
[        ]      /Users/will/.gradle/caches/transforms-2/files-2.1/dcdc98f5202138eb83b2d992b19de2af/play-services-ads-lite-19.6.0/AndroidManifest.xml:27:5-38:15: AAPT: error: unexpected element <queries> found in <manifest>.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 36s
[{"event":"app.progress","params":{"appId":"99583fca-ff91-439d-81be-cb9e58bc5344","id":"0","progressId":null,"finished":true}}]
[ +421 ms] The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
[   +7 ms] Building plugin admob_flutter...
Running Gradle task 'assembleAarRelease'...
[{"event":"app.progress","params":{"appId":"99583fca-ff91-439d-81be-cb9e58bc5344","id":"1","progressId":null,"message":"Running Gradle task 'assembleAarRelease'..."}}]
[   +5 ms] gradle.properties already sets `android.enableR8`
[   +3 ms] Using gradle from /Users/will/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-1.0.1/android/gradlew.
[        ] /Users/will/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-1.0.1/android/gradlew mode: 33261 rwxr-xr-x.
[        ] executing: [/Users/will/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-1.0.1/android/] /Users/will/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-1.0.1/android/gradlew -I=/Users/will/flutter/packages/flutter_tools/gradle/aar_init_script.gradle -Pflutter-root=/Users/will/flutter -Poutput-dir=/Users/will/flutter_workspace/projectx/build/app -Pis-plugin=true -PbuildNumber=1.0 -q -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease
[  +24 ms] env: sh\r: No such file or directory
[{"event":"app.progress","params":{"appId":"99583fca-ff91-439d-81be-cb9e58bc5344","id":"1","progressId":null,"finished":true}}]
[   +1 ms] env: sh\r: No such file or directory

[   +5 ms] Exception: The plugin admob_flutter could not be built due to the issue above.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:474:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```

**Comment by softronaut** [comment]
this https://github.com/kmcgill88/admob_flutter/issues/243#issuecomment-760820735 should solve your issue.

**Comment by willladislaw** [comment]
@softronaut  👍
