### ISSUE TITLE
Ad failed to load : 3 / Service not registered

### ISSUE THREAD

**Issue by trueToastedCode** [kmcgill88/admob_flutter#253]
I dont't know why this is happening...

build.gradle (app)
```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply plugin: 'com.google.gms.google-services'

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation platform('com.google.firebase:firebase-bom:26.3.0')
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation 'androidx.multidex:multidex: 2.0.1'
```

build.gradle
```
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.4'
    }
```

```
<meta-data
           android:name="com.google.android.gms.ads.APPLICATION_ID"
           android:value="ca-app-pub-3940256099942544~3347511713"/>
```
app id is from (https://pub.dev/packages/admob_flutter), but my own is not working either

```
@override
  void initState() {
    super.initState();
    WidgetsFlutterBinding.ensureInitialized();
    Admob.initialize();
  }
```

the main error:
```
W/ConnectionTracker(32693): Exception thrown while unbinding
W/ConnectionTracker(32693): java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.measurement.internal.zzjl@170b7d4
W/ConnectionTracker(32693): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1766)
W/ConnectionTracker(32693): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1810)
W/ConnectionTracker(32693): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:741)
W/ConnectionTracker(32693): 	at com.google.android.gms.common.stats.ConnectionTracker.zza(com.google.android.gms:play-services-basement@@17.3.0:55)
W/ConnectionTracker(32693): 	at com.google.android.gms.common.stats.ConnectionTracker.unbindService(com.google.android.gms:play-services-basement@@17.3.0:50)
W/ConnectionTracker(32693): 	at com.google.android.gms.measurement.internal.zzjm.zzF(com.google.android.gms:play-services-measurement-impl@@18.0.1:6)
W/ConnectionTracker(32693): 	at com.google.android.gms.measurement.internal.zziw.zza(com.google.android.gms:play-services-measurement-impl@@18.0.1:5)
W/ConnectionTracker(32693): 	at com.google.android.gms.measurement.internal.zzak.run(com.google.android.gms:play-services-measurement-impl@@18.0.1:5)
W/ConnectionTracker(32693): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/ConnectionTracker(32693): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker(32693): 	at com.google.android.gms.measurement.internal.zzfs.run(com.google.android.gms:play-services-measurement-impl@@18.0.1:6)
W/IInputConnectionWrapper(32693): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(32693): getTextBeforeCursor on inactive InputConnection
I/Surface (32693): opservice is null false
D/OnePlusJankManager(32693):  Chor uploadMDM JANK_TYPE_ONCE mViewTitle = com.truetoastedcode.bayanalytica6/com.truetoastedcode.bayanalytica6.MainActivity--- jank level = 1
W/System  (32693): A resource failed to call release. 
W/ConnectionTracker(32693): Exception thrown while unbinding
W/ConnectionTracker(32693): java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.measurement.internal.zzjl@170b7d4
W/ConnectionTracker(32693): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1766)
W/ConnectionTracker(32693): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1810)
W/ConnectionTracker(32693): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:741)
W/ConnectionTracker(32693): 	at com.google.android.gms.common.stats.ConnectionTracker.zza(com.google.android.gms:play-services-basement@@17.3.0:55)
W/ConnectionTracker(32693): 	at com.google.android.gms.common.stats.ConnectionTracker.unbindService(com.google.android.gms:play-services-basement@@17.3.0:50)
W/ConnectionTracker(32693): 	at com.google.android.gms.measurement.internal.zzjm.zzF(com.google.android.gms:play-services-measurement-impl@@18.0.1:6)
W/ConnectionTracker(32693): 	at com.google.android.gms.measurement.internal.zziw.zza(com.google.android.gms:play-services-measurement-impl@@18.0.1:5)
W/ConnectionTracker(32693): 	at com.google.android.gms.measurement.internal.zzak.run(com.google.android.gms:play-services-measurement-impl@@18.0.1:5)
W/ConnectionTracker(32693): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/ConnectionTracker(32693): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker(32693): 	at com.google.android.gms.measurement.internal.zzfs.run(com.google.android.gms:play-services-measurement-impl@@18.0.1:6)
```

**Comment by trueToastedCode** [comment]
Update: I fixed the "Service not registered: [...]" by adding implementation 'com.google.android.gms:play-services-basement:17.4.0'
However i still get the "Ad failed to load : 3" error

**Comment by trueToastedCode** [comment]
Fix: Set payment and wait 24h after creating firebase, etc...
